[{ 
    "orderHdrID": "Q8o1RD1CpDRyun9LvBRwNtVI2fn", 
    "originalID": "Q8o1RD1CpDRyun9LvBRwNtVI2fn", 
    "itemCode": "EP150751844VN", 
    "originalItemCode": "EP150751844VN", 
    "status": 14, 
    "saleOrderCode": "T0124080601010168", 
    "senderCode": "T001844476", 
    "senderContractNumber": "15082019/HĐNT3319", 
    "senderName": "NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN BẢN VIỆT", 
    "senderPhone": "+84991000000", 
    "senderEmail": null, 
    "senderAddress": "QUANG MINH MÊ LINH HN",
    "senderProvinceCode": "10", 
    "senderProvinceName": "TP. Hà Nội", 
    "senderDistrictCode": "1290", 
    "senderDistrictName": "H. Mê Linh", 
    "senderCommuneCode": null, 
    "senderCommuneName": null, 
    "senderPostcode": null, 
    "receiverCode": null, 
    "receiverName": "TRAN THI MINH HIEU", 
    "receiverContractNumber": null, 
    "receiverAddress": "CHUNG CU HACOM GALACITY, TOA A2,, KHU K1,PHUONG THANH SON,THANH PHO PHAN RANG-THAP CHAM,TINH NINH THUAN . TP. Phan Rang Tháp Chàm Tỉnh Ninh Thuận", 
    "receiverProvinceCode": "59", 
    "receiverProvinceName": "Tỉnh Ninh Thuận", 
    "receiverDistrictCode": "5910", 
    "receiverDistrictName": "TP. Phan Rang Tháp Chàm", 
    "receiverCommCode": "59108", 
    "receiverCommName": "P. Thanh Sơn", 
    "receiverPostcode": null, 
    "receiverPhone": null, 
    "receiverEmail": null, 
    "serviceCode": "ETN011", 
    "totalFee": 19656, 
    "mainFee": 14256, 
    "mainFeeBeforeTax": 13200, 
    "mainTax": null, 
    "vasFee": 5400, 
    "codAmount": null, 
    "addonService": [{ "code": "GTG004", "fee": 5400, "feeBeforeTax": 5000, "tax": null, "taxRate": null, "propList": [] }], 
    "additionRequest": [], 
    "weight": 35, 
    "length": 0, 
    "width": 0,
    "height": 0, 
    "dimWeight": 1, 
    "priceWeight": 35, 
    "deliveryInstruction": "Gọi điện trước khi giao, đối chiếu GTTT", 
    "quantity": 1, 
    "contentNote": "THE NGAN HANG^1^0^0", 
    "contentDetail": [], 
    "sendType": "2", 
    "isBroken": "false", 
    "deliveryTime": null, 
    "deliveryRequire": "1", 
    "vehicle": "Bay", 
    "awbNumber": null, 
    "voucher": null, 
    "orgCodeCollect": null, 
    "orgCodeAccept": "142240", 
    "createdBy": "142000_DUNGNT", 
    "createdDate": "06/08/2024 17:28:16", 
    "updatedBy": null, 
    "updatedDate": "20/08/2024 09:47:12", 
    "acceptedDate": null, 
    "sortingCode": null, 
    "paymentStatus": "0", 
    "caseTypeName": null, 
    "caseStatus": null, 
    "source": "BCCP", 
    "originalSource": "BCCP", 
    "inputType": null, 
    "inputMethod": null, 
    "methodPay": null, 
    "methodPayName": null 
}]